apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    descriptions: web server
    meta.helm.sh/release-name: mybuddy
    meta.helm.sh/release-namespace: mybuddy
  creationTimestamp: "2024-02-25T18:15:45Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: mybuddy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dify
    app.kubernetes.io/version: 0.4.9
    component: web
    helm.sh/chart: dify-0.17.0
  name: mybuddy-dify-web
  namespace: mybuddy
  resourceVersion: "454642"
  uid: 38c7c188-7448-4a52-95df-5f83cbd3e014
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mybuddy
      app.kubernetes.io/name: dify
      component: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mybuddy
        app.kubernetes.io/name: dify
        component: web
    spec:
      containers:
      - env:
        - name: EDITION
          value: SELF_HOSTED
        envFrom:
        - configMapRef:
            name: mybuddy-dify-web
        image: mybuddy.azurecr.io/mybuddy-web:v0.0.1
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-25T18:15:47Z"
    lastUpdateTime: "2024-02-25T18:15:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-25T18:15:45Z"
    lastUpdateTime: "2024-02-26T17:15:19Z"
    message: ReplicaSet "mybuddy-dify-web-75ff559779" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
