apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    descriptions: api
  labels:
    app.kubernetes.io/instance: mybuddy
    app.kubernetes.io/name: dify
    component: api
  name: mybuddy-dify-api
  namespace: mybuddy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mybuddy
      app.kubernetes.io/name: dify
      component: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mybuddy
        app.kubernetes.io/name: dify
        component: api
    spec:
      containers:
      - env:
        - name: CHECK_UPDATE_URL
        envFrom:
        - configMapRef:
            name: mybuddy-dify-api
        image: mybuddy.azurecr.io/mybuddy-api:latest
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 5001
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/api/storage
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: mybuddy-dify
