apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    descriptions: worker
  generation: 1
  labels:
    app.kubernetes.io/instance: mybuddy
    app.kubernetes.io/name: dify
    component: worker
  name: mybuddy-dify-worker
  namespace: mybuddy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mybuddy
      app.kubernetes.io/name: dify
      component: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mybuddy
        app.kubernetes.io/name: dify
        component: worker
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mybuddy-dify-worker
        image: langgenius/dify-api:0.5.6
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/api/storage
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: mybuddy-dify
